#include<Set>
#include<global.h>

enum flag {NONE, IMP, ALL};
enum METHOD_NAMES {
	NO_PREEMPT,
	ECB_ONLY,
	UCB_ONLY,
	UCB_UNION,
	ECB_UNION,
	ECB_UNION_MULTISET,
	UCB_UNION_MULTISET,
	ECB_UCB_UNION_MULTISET_COMBINED,
	ECB_UNION_MULTISET_PRE,
	UCB_UNION_MULTISET_PRE,
	ECB_UCB_UNION_MULTISET_COMBINED_PRE,
	STASCHULAT,
	STASCHULAT_PRE,
	PRE_MAX,
	PRE_MAX_KD,
	PRE_MAX_KD2,
	PRE_MAX_KD3,
	PRE_MAX_KD4,
	LEE_WODC,
	LEE_WDC,
	NUM_METHODS
};
int MESSAGE_LEVEL = ALL;
int VERBOSE = 1;
double C[NUM_TASKS];
long D[NUM_TASKS];
long T[NUM_TASKS];
double util;
std::set<int> TASK_ECB[NUM_TASKS], TASK_UCB[NUM_TASKS];
int Num_Executed_Tasks[NUM_METHODS];
